# -*- coding: utf-8 -*-

## Generally defaults set by MATLAB pre-processing
nameappend : spectrogram_trainedby_ 
hypFs : 2
winsize: 10

## WORKING_DIR should be the full path to where the data is located
WORKING_DIR : ?DIR

## SESSION_ID is the name of the file to be trained
SESSION_ID : ?SES

## Set TRUE to evaluate with ground truth in sleep_wake_classifier_predict.py
compareHypnograms: 0 
win:  32
modelCNN: 0

## currentModel is where the .h5 file is located. Typically in ./BrainState/DNN/python_build/
currentModel: ?PATH/BrainState/DNN/python_build/model_hypnogram

WORKING_DIR: "G:/sleep_DNN/data"
SESSION_ID: "02-25"
currentModel: "G:/sleep_DNN/data/model_hypnogram"